# Advertising Dataset Model

## Importing the Libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Importing the dataset

In [ ]:
dataset = pd.read_csv("Advertising.csv")
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [ ]:
X

array([[230.1,  37.8,  69.2],
       [ 44.5,  39.3,  45.1],
       [ 17.2,  45.9,  69.3],
       [151.5,  41.3,  58.5],
       [180.8,  10.8,  58.4],
       [  8.7,  48.9,  75. ],
       [ 57.5,  32.8,  23.5],
       [120.2,  19.6,  11.6],
       [  8.6,   2.1,   1. ],
       [199.8,   2.6,  21.2],
       [ 66.1,   5.8,  24.2],
       [214.7,  24. ,   4. ],
       [ 23.8,  35.1,  65.9],
       [ 97.5,   7.6,   7.2],
       [204.1,  32.9,  46. ],
       [195.4,  47.7,  52.9],
       [ 67.8,  36.6, 114. ],
       [281.4,  39.6,  55.8],
       [ 69.2,  20.5,  18.3],
       [147.3,  23.9,  19.1],
       [218.4,  27.7,  53.4],
       [237.4,   5.1,  23.5],
       [ 13.2,  15.9,  49.6],
       [228.3,  16.9,  26.2],
       [ 62.3,  12.6,  18.3],
       [262.9,   3.5,  19.5],
       [142.9,  29.3,  12.6],
       [240.1,  16.7,  22.9],
       [248.8,  27.1,  22.9],
       [ 70.6,  16. ,  40.8],
       [292.9,  28.3,  43.2],
       [112.9,  17.4,  38.6],
       [ 97.2,   1.5,  30. ],
       [26

In [ ]:
y

array([22.1, 10.4,  9.3, 18.5, 12.9,  7.2, 11.8, 13.2,  4.8, 10.6,  8.6,
       17.4,  9.2,  9.7, 19. , 22.4, 12.5, 24.4, 11.3, 14.6, 18. , 12.5,
        5.6, 15.5,  9.7, 12. , 15. , 15.9, 18.9, 10.5, 21.4, 11.9,  9.6,
       17.4,  9.5, 12.8, 25.4, 14.7, 10.1, 21.5, 16.6, 17.1, 20.7, 12.9,
        8.5, 14.9, 10.6, 23.2, 14.8,  9.7, 11.4, 10.7, 22.6, 21.2, 20.2,
       23.7,  5.5, 13.2, 23.8, 18.4,  8.1, 24.2, 15.7, 14. , 18. ,  9.3,
        9.5, 13.4, 18.9, 22.3, 18.3, 12.4,  8.8, 11. , 17. ,  8.7,  6.9,
       14.2,  5.3, 11. , 11.8, 12.3, 11.3, 13.6, 21.7, 15.2, 12. , 16. ,
       12.9, 16.7, 11.2,  7.3, 19.4, 22.2, 11.5, 16.9, 11.7, 15.5, 25.4,
       17.2, 11.7, 23.8, 14.8, 14.7, 20.7, 19.2,  7.2,  8.7,  5.3, 19.8,
       13.4, 21.8, 14.1, 15.9, 14.6, 12.6, 12.2,  9.4, 15.9,  6.6, 15.5,
        7. , 11.6, 15.2, 19.7, 10.6,  6.6,  8.8, 24.7,  9.7,  1.6, 12.7,
        5.7, 19.6, 10.8, 11.6,  9.5, 20.8,  9.6, 20.7, 10.9, 19.2, 20.1,
       10.4, 11.4, 10.3, 13.2, 25.4, 10.9, 10.1, 16

## Scaling the dataset

In [ ]:
# from sklearn.preprocessing import StandardScaler
# sc = StandardScaler()
# X = sc.fit_transform(X)

In [ ]:
# X

## Spliting the dataset into train and test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

In [ ]:
X_train

array([[109.8,  14.3,  31.7],
       [229.5,  32.3,  74.2],
       [253.8,  21.3,  30. ],
       [184.9,  21. ,  22. ],
       [ 44.7,  25.8,  20.6],
       [ 62.3,  12.6,  18.3],
       [292.9,  28.3,  43.2],
       [172.5,  18.1,  30.7],
       [202.5,  22.3,  31.6],
       [  7.3,  28.1,  41.4],
       [265.2,   2.9,  43. ],
       [197.6,   3.5,   5.9],
       [218.5,   5.4,  27.4],
       [147.3,  23.9,  19.1],
       [171.3,  39.7,  37.7],
       [217.7,  33.5,  59. ],
       [262.7,  28.8,  15.9],
       [163.5,  36.8,   7.4],
       [100.4,   9.6,   3.6],
       [ 76.3,  27.5,  16. ],
       [184.9,  43.9,   1.7],
       [134.3,   4.9,   9.3],
       [273.7,  28.9,  59.7],
       [296.4,  36.3, 100.9],
       [ 96.2,  14.8,  38.9],
       [109.8,  47.8,  51.4],
       [255.4,  26.9,   5.5],
       [204.1,  32.9,  46. ],
       [240.1,  16.7,  22.9],
       [193.7,  35.4,  75.6],
       [191.1,  28.7,  18.2],
       [ 89.7,   9.9,  35.7],
       [ 43. ,  25.9,  20.5],
       [ 3

In [ ]:
X_test

array([[ 69.2,  20.5,  18.3],
       [ 50. ,  11.6,  18.4],
       [ 90.4,   0.3,  23.2],
       [289.7,  42.3,  51.2],
       [170.2,   7.8,  35.2],
       [ 56.2,   5.7,  29.7],
       [  8.7,  48.9,  75. ],
       [240.1,   7.3,   8.7],
       [ 23.8,  35.1,  65.9],
       [197.6,  23.3,  14.2],
       [261.3,  42.7,  54.7],
       [ 87.2,  11.8,  25.9],
       [156.6,   2.6,   8.3],
       [187.8,  21.1,   9.5],
       [ 76.4,  26.7,  22.3],
       [120.2,  19.6,  11.6],
       [265.6,  20. ,   0.3],
       [  0.7,  39.6,   8.7],
       [ 74.7,  49.4,  45.7],
       [213.4,  24.6,  13.1],
       [287.6,  43. ,  71.8],
       [140.3,   1.9,   9. ],
       [175.1,  22.5,  31.5],
       [131.7,  18.4,  34.6],
       [ 53.5,   2. ,  21.4],
       [123.1,  34.6,  12.4],
       [165.6,  10. ,  17.6],
       [205. ,  45.1,  19.6],
       [224. ,   2.4,  15.6],
       [ 25.1,  25.7,  43.3],
       [ 67.8,  36.6, 114. ],
       [198.9,  49.4,  60. ],
       [280.7,  13.9,  37. ],
       [24

In [ ]:
y_train

array([12.4, 19.7, 17.6, 15.5, 10.1,  9.7, 21.4, 14.4, 16.6,  5.5, 12.7,
       11.7, 12.2, 14.6, 19. , 19.4, 20.2, 18. , 10.7, 12. , 20.7, 11.2,
       20.8, 23.8, 11.4, 16.7, 19.8, 19. , 15.9, 19.2, 17.3, 10.6,  9.6,
        7.6,  5.3, 15.7,  9.3, 18.4,  9.5, 12.8, 12.9,  8.6, 17.3, 11. ,
        9.7, 11.8, 27. ,  6.6, 22.2, 14.1,  7.3,  9.9, 11.4, 22.1, 11.5,
       13.4, 16.9, 18. , 12.2, 17.1, 22.3,  9.7, 14.8, 15.2,  9.7, 13.3,
       15.5, 10.3, 11.6, 18. , 22.4,  5.3, 20.7, 22.6, 11.7,  6.9, 18.5,
       12.2, 11.9, 25.5, 11.8, 18.9, 21.7,  7. ,  3.2, 14.5, 15.3,  7.3,
       13.4, 17.4,  6.6, 14.8, 12.8, 13.2,  9.3, 10.4, 15.5, 14.9, 20.7,
       19.2,  5.7, 11.7, 24.4, 10.1, 19.6, 21.2, 10.1, 24.7,  9.5, 18.9,
       14.6, 11.6, 11.9,  8. ,  8.8, 20.2,  9.6, 20.1, 15. , 25.4, 10.5,
       17.2, 11.3, 11. , 12.6, 10.9, 19.6,  8.8, 14.2, 12. , 11.9, 12.3,
       15.9, 11.5, 10.8, 21.5, 23.8, 10.9, 12.9, 18.3, 16. , 25.4, 12.5,
       10.6, 14.7, 13.4,  5.9,  9.4, 23.2,  7.6])

In [ ]:
y_test

array([11.3,  8.4,  8.7, 25.4, 11.7,  8.7,  7.2, 13.2,  9.2, 16.6, 24.2,
       10.6, 10.5, 15.6, 11.8, 13.2, 17.4,  1.6, 14.7, 17. , 26.2, 10.3,
       14.9, 12.9,  8.1, 15.2, 12.6, 22.6, 11.6,  8.5, 12.5, 23.7, 16.1,
       21.8,  5.6,  6.7,  9.7, 12.9, 13.6,  7.2, 10.8,  9.5, 15. , 15.9,
       17.1, 14. ,  4.8,  8.7, 15.9, 10.4])

## Training the Multiple Linear Regression Model

In [ ]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

## Predicting the test set result

In [ ]:
y_pred = regressor.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))


[[10.0494569  11.3       ]
 [ 7.43052335  8.4       ]
 [ 6.97152143  8.7       ]
 [24.16378667 25.4       ]
 [12.00215643 11.7       ]
 [ 6.54334645  8.7       ]
 [13.09526331  7.2       ]
 [14.95879164 13.2       ]
 [11.00528358  9.2       ]
 [16.27234553 16.6       ]
 [22.99324688 24.2       ]
 [ 9.12188347 10.6       ]
 [10.33545333 10.5       ]
 [15.39628185 15.6       ]
 [11.60589932 11.8       ]
 [12.11484332 13.2       ]
 [18.60251172 17.4       ]
 [10.81414474  1.6       ]
 [16.07541355 14.7       ]
 [17.22753644 17.        ]
 [24.2342995  26.2       ]
 [ 9.47711838 10.3       ]
 [15.13960412 14.9       ]
 [12.41064749 12.9       ]
 [ 5.67814427  8.1       ]
 [15.22889947 15.2       ]
 [12.21635459 12.6       ]
 [20.94370559 22.6       ]
 [13.28068231 11.6       ]
 [ 9.16578351  8.5       ]
 [13.30285718 12.5       ]
 [21.5770033  23.7       ]
 [18.098111   16.1       ]
 [21.15572322 21.8       ]
 [ 6.69734039  5.6       ]
 [ 6.15355714  6.7       ]
 [ 7.96280151  9.7       ]
 

## Testing the accuracy of the model

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.8576396745320894